### ISSUE TITLE
Attention-OCR theano based !

### ISSUE THREAD

**Issue by goodtogood** [da03/Attention-OCR#1]
Hi there,
Is there any plan for  theano based Attention-OCR ?
Best regards,

**Comment by imoonkey** [comment]
Thanks for your interest. We are currently working on a torch implementation of Attention-OCR. A theano implementation might also be added later. Meanwhile, since tensorflow and theano work under similar mechanisms, you can refer to our current code for the idea. Keep tuned :)

**Comment by goodtogood** [comment]
got it ! 
THX!
