### ISSUE TITLE
Run error: TypeError("'Tensor' object is not iterable.")

### ISSUE THREAD

**Issue by striversist** [da03/Attention-OCR#11]
hi guys, 

When I run "python src/launcher.py --phase=train --data-path=sample/sample.txt --data-base-dir=sample --log-path=log.txt --no-load-model", the following errors came out:

Traceback (most recent call last):
  File "src/launcher.py", line 129, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 125, in main
    session = sess)
  File "/home/aaron/projects/Attention-OCR/src/model/model.py", line 164, in __init__
    for old_value, new_value in cnn_model.model.updates:
  File "/home/aaron/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 495, in __iter__
    raise TypeError("'Tensor' object is not iterable.")
TypeError: 'Tensor' object is not iterable.

**Comment by da03** [comment]
It seems to be an issue with a update of keras. I would sugget commenting line 164 and line 165, since they only affect the BatchNormalization layer in the CNN model, which does not affect the performance much (or at all).

**Comment by striversist** [comment]
Thanks. My Keras version is (1.0.8)
What's yours?

**Comment by striversist** [comment]
After I downgrade the keras version to 1.0.1, the problem disappeared.

**Comment by Yang507** [comment]
@striversist  can you tell me how can i get the Keras version 1.0.1? I use the command `pip -H install keras=1.0.1`, but `no module named keras`, thank you!
