### ISSUE TITLE
train fail

### ISSUE THREAD

**Issue by Yang507** [da03/Attention-OCR#18]
hello, I tried to train your data with your code, I use the tensorflow as the backend and I meet a problem. how can i solve it? I’d like to receive your answer, thanks!

    File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 496, in __iter__
     raise TypeError("'Tensor' object is not iterable.")
    TypeError: 'Tensor' object is not iterable.

**Comment by da03** [comment]
Oh that should be an issue with the new keras version. Try downgrade the keras version to 1.0.1.

**Comment by Yang507** [comment]
sorry, i've tried some methods but i didn't solve the keras' downgrade problem, could you give me some suggestions?my keras' version is 1.1.1, thank you!

**Comment by da03** [comment]
Okay I'll look into this problem and get back after fixing it. A temporary solution is to comment those lines, which means opting out the batch normalization layers. That might lead to slower convergence or poorer optimum.

**Comment by Yang507** [comment]
I used the keras version 1.0.4 [https://testpypi.python.org/pypi/Keras]() can run, the problem had been solved!

**Comment by Yang507** [comment]
I used the keras version 1.0.4([ https://testpypi.python.org/pypi/Keras](url)) can run, the problem had been solved.

**Comment by da03** [comment]
I just updated a version which supports the latest tensorflow and keras. However, it might not be able to run on the older version tensorflow and keras. The original implemenation is in branch `old`.
