### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Yang507** [da03/Attention-OCR#19]
when I train my data, the accuracy is one substract the loss value ?

**Comment by da03** [comment]
Sorry that I might not understand, if we train the model, the log file will output the perplexity values. Accuray will be evaluated when we are testing the model.

**Comment by Yang507** [comment]
In fact I'm not understand the perplexity value, i don't know the meaning of it.

**Comment by da03** [comment]
I see. Perplexity is a common measurement for evaluating language model. It represents the average uncertainty of predicting a symbol. For example, if we have a perplexity of 2, that means the model needs to guess on average 2 times for each character to get the correct one. Therefore, the ideal perplexity shall be 1, which means the model guess once, and gets the correct prediction. I would recommend reading wikipedia for a reference: https://en.wikipedia.org/wiki/Perplexity.

**Comment by Yang507** [comment]
Thank you for answering my doubts!

**Comment by da03** [comment]
You are welcome!
