### ISSUE TITLE
Question about training procedure

### ISSUE THREAD

**Issue by chenmulin** [da03/Attention-OCR#27]
I train the model on my own dataset, which contains 10k plate images. 
When I set the batch_size as 256, the step perplexity reaches to 1.001, however, the step perplexity of the trained model increases to 10 if the batch_size is set to 2.
If I fix the batch_size to 256, does the model really converge?
I wonder that a large batch_size is not appropriate.

**Comment by chenmulin** [comment]
In addition, I have another question. I found the losses of the same data are different during training and testing. Looking forward to an answer, thanks!

**Comment by ddaue** [comment]
I solved it with the following modification in model.py, line 352, without any explanations of why it should be like that... I searched a lot...

#if not forward_only:
if True:
input_feed[K.learning_phase()] = 1
else:
input_feed[K.learning_phase()] = 0

**Comment by chenmulin** [comment]
It works!
Without your help, I will never find out this single detail!
Thank you a lot! Very grateful for you help and patience!


------------------
Best Wishes,
Mulin Chen

2017-02-23 2:09 GMT+08:00 ddaue <notifications@github.com>:
