### ISSUE TITLE
Accuracy on SVT data set

### ISSUE THREAD

**Issue by gorinars** [da03/Attention-OCR#3]
I was trying to evaluate the performance of your tool on SVT test data

As suggested by README, I downloaded the model from http://www.cs.cmu.edu/~yuntiand/model.tgz and the data from http://www.cs.cmu.edu/~yuntiand/evaluation_data.tgz

After running 

`python src/launcher.py --phase=test --visualize --data-path=evaluation_data/svt/test.txt --data-base-dir=evaluation_data/svt --log-path=log.txt --load-model --model-dir=model --output-dir=results
`

I get 

```
INFO     3.166667 out of 6 correct

...

INFO     437.192016 out of 647 correct
```

I was expecting to get about 80% accuracy, but the results seem to be worse. 

Do you know what is the expected accuracy of this tool with the provided model and how it can possibly improved to achieve state-of-the art result?

Thanks

**Comment by da03** [comment]
The provided model is a small one. In order to achieve state-of-the-art performance, a larger model needs to be trained. You can increase the model capacity by setting `attn-num-hidden` and `attn-num-layers` to a larger value.

**Comment by gorinars** [comment]
Thank you. 

I wonder if you tried different values and have an idea about the optimal ones in terms of size/accuracy for training of 90k synt set?

**Comment by imoonkey** [comment]
Hi there. Thanks for your interest! Limited by time and computation resources, we have not heavily tuned the parameters. We are not really sure what are the optimal hyper-parameters. You are welcome to try training with different parameters and tuning the network architecture.

**Comment by gorinars** [comment]
Great. Thanks!

**Comment by pasha76** [comment]
@gorinars did you try to tune the parameters? Any improvement? Any optimal value for parameters? Thanks in adavnce
