### ISSUE TITLE
warning in train - tf 0.9

### ISSUE THREAD

**Issue by avr248** [da03/Attention-OCR#5]
tf - 0.9

WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x11db4fb50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.

**Comment by da03** [comment]
Sorry that we do not have time to solve this warning now, you are very welcome to solve this and send us a pull request.
