### ISSUE TITLE
traing on Synth 90K data set

### ISSUE THREAD

**Issue by gorinars** [da03/Attention-OCR#6]
Hi,

I am trying to train the model using Synth 90K data set. I downloaded the data set and shuffled the transcriptions (annotation.txt with about 9M records) before training. After 40k steps I get the perplexity about 5.0, and then testing on SVT data set I get much worse result than with the model you provided.

I therefore just wonder if you could share the setup you used to train your model. Did you use the whole data set, or some additional filtering was applied (I see in config some file mnt/train_shuffled_words.txt)? Or maybe you used some additional options besides those stated in README?

Thanks in advance

**Comment by LinJM** [comment]
I use the whole Synth 90K data set to train the model, after 200k steps I get the perplexity about 1.35, and then testing on SVT data set I get accuray about 66%. 
I also use iiit5k train set to train the model, although I quickly get the perplexity to 1.0, but when I test the model on iiit5k test set, the accuray is very poor.

**Comment by gorinars** [comment]
Thanks for the input. It's interesting because the attached model seems to converge after 47k iterations. Anyway, will try to keep it running a little longer.

**Comment by avr248** [comment]
@LinJM how many files you train in "new_annotation_train.txt",
(i assume that is edit annotation_train.txt file).
