### ISSUE TITLE
Resume Training from Checkpoint

### ISSUE THREAD

**Issue by AdamWP** [da03/Attention-OCR#62]
Is it possible to resume training from a checkpoint if training was interrupted?

**Comment by pannous** [comment]
yes

**Comment by famunir** [comment]
Can you please tell in bit more detail how to do that? @pannous 
@AdamWP If you know the solution to this now, can you please detail that here?
Thank you!

**Comment by AdamWP** [comment]
@famunir If you run the training session again with the same model_dir it will resume from the last checkpoint automatically.
