### ISSUE TITLE
100% incorrect

### ISSUE THREAD

**Issue by kspook** [da03/Attention-OCR#89]
hi..    i tried "test and visualization attention results.

i got 100% incorrect.

what is the problem? T.T

**Comment by XuXuanhui** [comment]
maybe you forget to download the model

**Comment by kspook** [comment]
Downloaded model is ok.
but when I trained the model with toy exmple and tested with downloaded data, 
I got 100% incorrect.

**Comment by kspook** [comment]
I put the wrong model directory.
Thanks.
